### ISSUE TITLE
Air pollution (DEFRA)

### ISSUE THREAD

**Issue by georgerichardson** [nestauk/beis-indicators#108]
**Summary**
- Date: 2007 - 2018
- Sources: [DEFRA](https://uk-air.defra.gov.uk/data/pcm-data#pm10)

**Progress**
- [x] Scoped
- [x] Collected
- [x] Transformed
- [x] Uploaded
- [x] Raw Schema
- [x] Processed
- [x] Processed Schema
- [ ] NUTS3
- [ ] LEPs

**Challenges and Observations**
- Many different pollution types available. Will use PM10 for now.
- Available at EPSP:27700 (BNG). Will need converting to lat lon and then NUTS2

**Comment by mindrones** [comment]
Reopening because https://github.com/nestauk/beis-indicators/blob/dev/data/processed/defra/air_pollution_mean_pm10.csv still has the index column. @georgerichardson

**Comment by mindrones** [comment]
The current schema (merged in a previous PR) [1] has:
```
endpoint_source: https://uk-air.defra.gov.uk/data/pcm-data
```
but at https://uk-air.defra.gov.uk/data/pcm-data there are multiple files for different PM sizes, so we should use a list of csvs used to build this indicator rather than just providing that index page.

[1] https://github.com/nestauk/beis-indicators/blob/dev/data/processed/defra/air_pollution_mean_pm10.yaml

EDITT: addressed by #140

**Comment by mindrones** [comment]
Removal of the index column addressd by #142, closing
