### ISSUE TITLE
No type for percentage

### ISSUE THREAD

**Issue by georgerichardson** [nestauk/beis-indicators#246]
In the APS schemas under the fields `schema` -> `value` there is no `type` information. Instead there is a `label` and `unit_string`.

Noticed this while trying to automatically parse schemas and extract units. @Juan-Mateos @mindrones not sure if this is intentional or a bug, so feel free to close this if I'm wrong on this!

**Comment by mindrones** [comment]
It is intentional, as the percentage is not supposed to be a type, but rather a unit.
Unless the variable has a specific well known type we should use `%` as the [`unit_string`](https://github.com/nestauk/beis-indicators/blob/dev/ds/data/schema/schema_template.yaml#L41). If the variable has a type, the unit string should be indicated in that type definition.

**Comment by georgerichardson** [comment]
Ok. Is it documented anywhere? Doesn't seem super intuitive that a schema can have different fields for a value without some prior knowledge.

**Comment by mindrones** [comment]
[It is](https://github.com/nestauk/beis-indicators/blob/be4319068a233e0cd217cc0518d7a2bc408e1574/ds/data/schema/schema_template.yaml#L41). Right now it says:
`unit_string: string # OPTIONAL - the unit of measure, should we not provide a `type`. E.g. '%' for percentages.`

> that a schema can have different fields for a value without some prior knowledge.

What do you mean?

**Comment by mindrones** [comment]
I've clarified this [here](https://github.com/nestauk/imt_playbook/tree/dev/specs#percentage) so to eliminate this ambiguity. This is going to be the new format and documentation so I'll soon update the beis schema docs accordingly, hope it helps!
